CONTROL OpenCD-ROM
{
  TYPE			icon
  CONTAINER_NAME	Switch
  CONTAINER_TYPE	SWITCH
  POSITION_HINTS	4
  ICON			cdrom
  LABEL			Open CD
  PUSH_ACTION		OpenCD-ROM
  HELP_TOPIC		FPOnItemHome
  HELP_VOLUME		FPanel
}

