CONTROL	_ezExit_5
{
   TYPE	icon
   CONTAINER_TYPE	SWITCH
   CONTAINER_NAME	_ezSwitch_10
   POSITION_HINTS	4
   ICON	Fpexit
   LABEL	Exit
   PUSH_ACTION	ExitSession
   DELETE	false
   HELP_VOLUME	FPanel
   HELP_TOPIC	FPOnItemExit
}
