/* XPM */
static char * staroffice_m_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 13 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #000000008080",
"X	c #808080808080",
"o	c #C0C0C0C0C0C0",
"O	s iconColor2	m white	c white",
"+	s iconColor7	m white	c cyan",
"@	s iconColor8	m black	c magenta",
"#	c #808000008080",
"$	s iconColor6	m white	c yellow",
"%	s iconColor1	m black	c black",
"&	c #808080800000",
"*	c #000080808080",
"=	c #808000000000",
/* pixels */
" ....                           ",
"X.oO...                         ",
".oX+o+..                        ",
".@.o@Xo#X                       ",
".oX+X@+##X                      ",
".@.o+oXoo#X X                   ",
"...XoooXooX .X                  ",
".@ooXoXo$oX .                   ",
"..@oooo$O$OX .                  ",
".@XooXoOX#$X %.    .X           ",
".X@XXXX$XXOoX X...%%            ",
" .XXXX@XX$oXX#oX    ......X     ",
" .oXX@X@Xo#X##X#XXoXXoXX#X...X  ",
"  .oXX@XooXo.X#.ooooO$$$Xo+@o@X ",
"  .o#@oXXoX&##.XXOXXOOXO+@X+Xo. ",
" .X##Xo*oo+#.#&#XoXX$$X$oX@+X@. ",
".o#Xoo*XooX.#.+XooooOo$oo++X.o. ",
".XX#XoXXoO#..XoooX@XXXooXXXX@=. ",
".XoXXooX$X#.#OooX@X@XooooXX@=X  ",
".o.X.ooX$.#.X$o*@X@XoXooXXX@=   ",
" XXoXXXo$..X$XX*o#XXXoXXXX@=    ",
" .X%#.Xo$..$oXXXoX#ooXXX@==     ",
" XXooX&XX$$oXoooo##X...#=       ",
" #.**X&*oXXXXXXoXX..            ",
"X*% ..%  *X#X.XXX#X.            ",
".%       .&X##o.oXo.            ",
"%%       %.Xo.oXoo.             ",
"           .oXX..               ",
"           %*#                  ",
"            *X                  ",
"           X#                   ",
"          X%X                   "};
