/* XPM */
static char * staroffice_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 12 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #000000008080",
"X	c #808000008080",
"o	c #C0C0C0C0C0C0",
"O	c #808080808080",
"+	s iconColor2	m white	c white",
"@	s iconColor1	m black	c black",
"#	s iconColor8	m black	c magenta",
"$	s iconColor6	m white	c yellow",
"%	c #808000000000",
"&	c #808080800000",
"*	c #000080808080",
/* pixels */
"  .....                                         ",
"  X oOXOX                                       ",
" .OOOXooo.                                      ",
".oooXO++oo.                                     ",
".O@XOoooooo.                                    ",
".oOOXooOoooo.                                   ",
".ooXOo#O#oooXX                                  ",
"XoOOXoO#OoOXOXO                                 ",
".++XOooo+oOoooXO                                ",
".oO.XOo+oo+ooooX   .O                           ",
".OOXOXOOo+oOooooO  Oo                           ",
".oXO+$OOooOoooooX  O                            ",
".OOO$$ooooO$++++oX OO                           ",
".oOO$+ooOo+$o+oO+O  Oo                          ",
".oOO$ooooOo+ooOXooX o%        .o                ",
"XoO$$##oOOo+OXXoo$O  O%      OO                 ",
" .OOoOOOOOOooOOo$$$O O%o%%OOOO                  ",
" XoO#oooOOOOOoo$$O$XOOo%O      O..........      ",
"  XoOOOOooOOOo$OOXOXXXOX   ..X..ooooooooOX..    ",
"   .oOoOOOO#OoOOXO$XXoX.oX.oo+ooooooXOXOXOXOX.  ",
"    .oOOOOoOOoo&XOO.Oo.XO$$$ooo+oooX#Xoo+oooOX. ",
"    .ooooooo#OOO&&OXOX.&OX$+oXO$++O#oOooOoo+XOo.",
"   .ooXoXXoOo#ooo$XXX.O$OX$+OXo+$+#o+oo#O#ooOXo.",
"  .+oXOXOoo*Oooo+OXOXO&OXO$$oXO$$$OooooO#Ooo.OoX",
" .oXXXXO#o**ooo+oXOOX.@OOO$ooOo++oO+oo+ooooXOoO.",
" .oXXo#ooO*OooooXXX..OoOooOOooooooo+OOooo#OO@O. ",
".oOXXXXooO*ooooOXX.XXOooOooXOOOOOooooOOOOOXXoOX ",
".oO$$Xo#oooOOooXXX.X@ooooOOOOOOOoOoOoo$OXOXoo.  ",
".oo#$OXOooo+ooOXO.X@OoooO#O#O#OOOoOoo$$OO#oo.   ",
" .ooOXXO#ooO$+XXX.XOoooO*O#O#OooOooo$OO.XXoX    ",
" .OooO$OOo#O$$XX..@ooooO*oXoOoOooooo$O.oooX     ",
" .oooOO.OOO$$$XX.@ooooo**oXOoOoOoo$$OOoOoX      ",
"  .ooOXXXXOO+O**O+$oOoO*ooOoXooOOOOOO+oOX       ",
"   .OOOXOXoOO. .$$$+oooOooXoXoOOooooo.X.        ",
"   Xo++oO&Ooo. o++$OooooooXXXo. .....           ",
"  XO***oo&OO. .o$OO#ooooOOoXO+.                 ",
" OX*X..**OO.  .oOO.OO#O#oX#XXo.                 ",
" X*o   .*..   .OOOXOOOOXXOXXXo.                 ",
"XOO           XO&XX.XoXXO+oXo.                  ",
"X.            X&O$OXXOXXoooOo.                  ",
"@@            .**oo$.o#OOooo.                   ",
"               .X**+OOoooo..                 @@ ",
"                 O*oO.....                  @  @",
"                  X*X                       @  @",
"                  O*X                        @@ ",
"                  *X                        @  @",
"                  OX                        @  @",
"                 ..X                         @@ "};
