/* XPM */
static char * staroffice_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"24 24 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	c #000000008080",
"X	c #C0C0C0C0C0C0",
"o	c #808080808080",
"O	c #808000008080",
"+	s iconColor7	m white	c cyan",
"@	s iconColor2	m white	c white",
"#	s iconColor1	m black	c black",
"$	c #000080808080",
"%	s iconColor6	m white	c yellow",
/* pixels */
" ....                   ",
".XoXo.                  ",
".ooXXo.                 ",
".oXoXoO.                ",
".o+@XXX.  #             ",
".o@+XXXX. #             ",
".o@XXX@XO #             ",
".oXXoXooXO #  ##        ",
".oXooooXXO Oo##         ",
" .XoooooooOOo  ........ ",
" .XXXXXooOOOo..XXoXXXXo.",
".XXoooXXXOO.oXoX@XXXoXo.",
".ooo@$XXOOOooXXXXXo@@oo.",
".oooooXoOO.XXoooX@@++oX#",
".XooX%%OOOXXoXoooX@ooX# ",
".XXooo%O.XXXooooXXooX#  ",
" .oOOo%$%%%oXoXoXoX.#   ",
" OoXooOo%o%@ooXOOO#  ## ",
" oOO$O oooooooXO    #  #",
" #  .  OoOooXo.     #  #",
"#      OoXoXX.#      ## ",
"        #oo.O         # ",
"         ##          #  ",
"        #O              "};
