CONTROL	_ezOpenCD-ROM_2
{
   TYPE	icon
   CONTAINER_TYPE	SWITCH
   CONTAINER_NAME	_ezSwitch_4
   POSITION_HINTS	4
   ICON	cdrom
   LABEL	Open CD
   PUSH_ACTION	OpenCD-ROM
   DELETE	false
   HELP_VOLUME	FPanel
   HELP_TOPIC	FPOnItemHome
}
